### ISSUE TITLE
Introduce a BGP maximum-prefix restart timer to set a proper timeout

### ISSUE THREAD

**Issue by suckowbiz** [metal-stack/metal-networker#1]
Within BGP context:

When a client's prefix announcement exceeds the maximum number the BGP session is **idled**. To control the restart of the BGP session is considered  a good practice because it helps to save resources. Unfortunately a configuration of `restart` did not succeed. 

The `restart 5` has no effect. It should ensure the next connection trial is retried 5 mins in advance and not adhoc. 

```
router bgp 4200004711 vrf vrf4711
 bgp router-id 10.0.0.11
 bgp bestpath as-path multipath-relax
 neighbor MACHINE peer-group
 neighbor MACHINE remote-as external
 neighbor MACHINE timers 1 3
 neighbor swp1 interface peer-group MACHINE
 neighbor swp2 interface peer-group MACHINE
 !
 address-family ipv4 unicast
  redistribute connected
  neighbor MACHINE maximum-prefix 100 restart 5
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
 exit-address-family
!
```

As it turns out this behavior is considered is a bug. It is tracked at Cumulus Linux with issue id `CM-24894.` It is issued for the 4.x Cumulus release.

**Comment by Gerrit91** [comment]
Please re-open if necessary.
