### ISSUE TITLE
machines also losing in-partition connectivity in case of loss of external internet connectivity

### ISSUE THREAD

**Issue by mwennrich** [metal-stack/metal-networker#48]
In the case where a partition loses its external internet connectivity (e.g. failure/maintenance at internet backbone routers) and doesn't get a default route announced from the isp-backbone, all machines are also losing their default route and therefore do not have a route to other internet addresses in the same partition:

```
May 12 05:23:42 shoot--prod--fel-wps101-default-worker-69c8dd77df-bgsd8 bgpd[1371]: Tx route delete VRF 0 0.0.0.0/0
May 12 05:29:43 shoot--prod--fel-wps101-default-worker-69c8dd77df-bgsd8 bgpd[1371]: Tx route add VRF 0 0.0.0.0/0 metric 0 tag 0 count 2
```

In the case of Kubernetes this e.g. results in a loss of the connection to the apiserver (in the same partition), though the apiserver is still running and could technically still be reachable. But neither have the shoot-machines a route to the apiserver, nor have the seed-machines a route back to the IP address of the shoot-firewall.

The reason is, that we only leak the full default route, not the single host routes to the machines.

`ip prefix-list vrf225-import-prefixes seq 100 permit 0.0.0.0/0`

Option a) Do not only leak the default route to the worker machines on the firewall but announce statically.

Option b) Also leak the internet host routes to the worker machines, like
```
ip prefix-list vrf225-import-prefixes seq 100 permit 0.0.0.0/0
ip prefix-list vrf225-import-prefixes seq 101 permit 185.153.67.0/24 le 32
ip prefix-list vrf225-import-prefixes seq 102 permit 212.34.89.0/25 le 32
(etc)
```
/cc @majst01 @mwindower @mreiger

**Comment by mwindower** [comment]
Voting for option b) as dynamic route leaking in combination with static networks has some issues.
