### ISSUE TITLE
if clusters behind dmz have a storage network attached, default route is learned from storage network

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-networker#61]

**Comment by majst01** [comment]
Solution #1, more a workaround:

on the storage firewall we modify the frr.conf as following:

```
--- frr.conf.before.change.no.export    2021-07-13 15:17:34.801715722 +0200
+++ frr.conf    2021-07-13 16:36:13.318656814 +0200
@@ -43,6 +43,7 @@
  !
  address-family l2vpn evpn
   neighbor FABRIC activate
+  neighbor FABRIC route-map evpn-out out
   advertise-all-vni
  exit-address-family
 !
@@ -106,6 +107,9 @@
  match as-path SELF
 route-map only-self-out deny 20
 !
+route-map evpn-out permit 10
+ set as-path prepend 4220000000
+!
 route-map LOOPBACKS permit 10
  match interface lo
 !
```

This will extend the as-path by one ASN and the worker nodes in the dmz cluster will pick the other route which has a shorter path.

**Comment by mwindower** [comment]
Since Frr 7.2 https://github.com/FRRouting/frr/pull/3827 should be included which allows to filter based on which VRF a route origintates from - so the rough `import vrf route-map rm` can be enriched with e.g. `match source-vrf vrf104009`.

See https://github.com/FRRouting/frr/blob/frr-7.2/bgpd/bgp_routemap.c#L1014 for documentation.

**Comment by mwennrich** [comment]
frr.conf on the behind-dmz-firewall:

```
# vrf64 = behind-dmz-worker-vrf
# vrf63 = dmz-worker-vrf
# vrf20 = storage-net

router bgp 4210000070 vrf vrf64
 bgp router-id 10.0.0.6
 bgp bestpath as-path multipath-relax
 !
 address-family ipv4 unicast
  redistribute connected
  import vrf vrf63                                               # extneral vrf
  import vrf vrf20                                               # storage vrf
  import vrf route-map vrf64-import-map                          # node-vrf
```

imho the firewall should not import everything from the storage-vrf, but just only the storage-net prefix?

**Comment by majst01** [comment]
But the question is how we identify the storage network as such, currently the network is only marked as "shared", the same applies for the dmz network from which we require to import all routes.

**Comment by mwennrich** [comment]
dmz-networks are external-networks (`network.metal-stack.io/default-external`), for these import everything.

for any other shared-network only import the prefix?
```yaml
name: partition-storage
shared: true
prefixes:
    - 10.131.44.0/22
```

**Comment by majst01** [comment]
Yes !

**Comment by mwindower** [comment]
The second solution idea with a source vrf filter looks like this:

```
ip prefix-list vrf64-import-prefixes seq 100 permit 10.128.148.0/22 le 32
ip prefix-list vrf64-import-prefixes seq 101 permit 10.131.44.0/22 le 32
route-map vrf64-import-map permit 10
 match ip address prefix-list vrf64-import-prefixes
!
ip prefix-list vrf64-import-vrf63 permit 0.0.0.0/0
!
route-map vrf64-import-map permit 11
 match source-vrf vrf63
 match ip address prefix-list vrf64-import-vrf63
!
route-map vrf64-import-map deny 20
```

This was successfully validated in our test partition: only 0/0 from the DMZ network is imported
