### ISSUE TITLE
Raise keepalive and hold time for local peers

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-networker#67]
currently we have set:
```
 neighbor LOCAL peer-group
 neighbor LOCAL remote-as internal
 neighbor LOCAL timers 1 3
```
Which configures the connection between the metallb-speaker and the bgpd. If the speaker is restarted, after 3 seconds the announced routes are withdrawn. We propose to raise this to `3 10` at least.

Related:

- https://github.com/metal-stack/gardener-extension-provider-metal/pull/190

**Comment by Gerrit91** [comment]
Everything is by now on `2 8`.
