### ISSUE TITLE
Setup VPN connection on machine

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [metal-stack/metal-networker#80]
`metal-networker` should be able to setup VPN connection if required config is provided via `install.yaml`. That requires 2 changes:

1. Create unit file to start `tailscaled` and connect to VPN
2. [Allow access to machine only via VPN](https://github.com/metal-stack/metal-networker/issues/78)

**Comment by Gerrit91** [comment]
I think this is done, closing.
